name: CI
on:
  push:
    branches: [ main ]

# Thần chú để bỏ qua cảnh báo Node.js và ép chạy bản mới nhất
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Thiết lập Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2. Cài đặt các thư viện hệ thống
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libunwind-dev
          sudo apt-get install -f
          sudo apt-get install -y \
            build-essential \
            git \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            libssl-dev \
            libffi-dev \
            zip \
            unzip \
            autoconf \
            libtool \
            pkg-config

      # 3. Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      # Cài API 35 và chấp nhận các điều khoản tự động
      - name: Install Android API 35
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-35" "build-tools;35.0.0"

      # 4. Cài đặt Buildozer và Cython
      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install "buildozer>=1.5.0" "cython<3.0"

      # 5. Cache Buildozer (Key v9 - Đổi key để đảm bảo nhận file mới)
      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-v9-${{ hashFiles('buildozer.spec') }}

      # 6. Build App (Chế độ Release + Ký tên tự động)
      - name: Build with Buildozer
        env:
          # Đây là lúc robot móc chìa khóa và mật khẩu từ Secrets ra dùng
          P4A_RELEASE_KEYSTORE: steven.keystore
          P4A_RELEASE_KEYALIAS: stevenapp
          P4A_RELEASE_KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASSWORD }}
          P4A_RELEASE_KEYALIAS_PASS: ${{ secrets.KEYSTORE_PASSWORD }}
          ACCEPT_SDK_LICENSE: "True"
        run: |
          buildozer android release

      # 7. Upload file .AAB thành phẩm
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RandomSTEVEN-AAB
          path: bin/*.aab
